/*
 * Monitoring Nilai Siswa
 *
 * API for Monitoring Nilai Siswa
 *
 * API version: 1
 * Contact: aribprasetyo88@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	IdAdmin string `json:"id_admin,omitempty"`

	IdGuru string `json:"id_guru,omitempty"`
}
