/*
 * Monitoring Nilai Siswa
 *
 * API for Monitoring Nilai Siswa
 *
 * API version: 1
 * Contact: aribprasetyo88@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	IdSiswa string `json:"id_siswa,omitempty"`

	NamaSiswa string `json:"nama_siswa,omitempty"`

	Nilai float64 `json:"nilai,omitempty"`
}
