/*
 * Monitoring Nilai Siswa
 *
 * API for Monitoring Nilai Siswa
 *
 * API version: 1
 * Contact: aribprasetyo88@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {

	Success bool `json:"success,omitempty"`
}
